name: Docker CI Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (optional for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker using GitHub credentials
      - name: Log in to Docker Hub using GitHub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}  # GitHub token

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t daniellem62/your-image-name:${{ github.sha }} .

      # Step 5: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push daniellem62/your-image-name:${{ github.sha }}

      # Optional: Step 6: Deploy to production (example deployment step)
      - name: Deploy to Production
        run: |
          # Your deployment steps (e.g., SSH into server or Kubernetes deployment)
